[package]
name = "archway-proto"
version = "0.1.0"
edition = "2021"
description = "Rust build of Archway's protobuf definitions"
authors = ["Augusto Elesbão <aelesbao@users.noreply.github.com>"]
categories = [
  "cryptography",
  "cryptography::cryptocurrencies",
  "database",
  "wasm",
]
keywords = [
  "archway",
  "blockchain",
  "cosmos",
  "cosmwasm",
  "proto",
  "productivity",
  "smart-contracts",
  "tendermint",
]
license = "Apache-2.0"
repository = "https://github.com/archway-network/archway-bindings"
homepage = "https://archway.io"
readme = "README.md"

[dependencies]
prost = "0.11.9"
prost-types = "0.11.9"

# cosmos-sdk-proto@0.18.0 is the latest version for the cosmos-sdk 0.45.x protos
cosmos-sdk-proto = { version = "0.18.0", default-features = false }

tonic = { version = "0.9", optional = true, default-features = false, features = [
  "codegen",
  "prost",
] }

[build-dependencies]
error-chain = "0.12.4"
glob = "0.3.1"
tonic-build = "0.9.2"
