[package]
name = "archway-bindings"
version = "0.2.0"
edition = "2021"
description = "CosmWasm bindings to interact with Archway's modules"
authors = ["Augusto Elesbão <aelesbao@users.noreply.github.com>"]
categories = [
  "cryptography",
  "cryptography::cryptocurrencies",
  "database",
  "wasm",
]
keywords = [
  "archway",
  "blockchain",
  "cosmwasm",
  "smart-contracts",
  "wasm",
]
license = "Apache-2.0"
repository = "https://github.com/archway-network/archway-bindings"
homepage = "https://archway.io"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]
staking = ["cosmwasm-std/staking"]

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
